version: "3.7"
services:
  mysql:
    image: yobasystems/alpine-mariadb
    container_name: mysql
    env_file:
      - database.env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - '8080:80'
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
volumes:
  mysql-data:
    driver: local
